---
# - name: Update APT cache
#   ansible.builtin.apt:
#     update_cache: true
#     cache_valid_time: 3600
#   when: ansible_os_family == 'Debian'

- name: Install nginx and dependencies
  ansible.builtin.package:
    name:
      - nginx
      - unzip
    state: present

- name: Install ModSecurity WAF
  ansible.builtin.package:
    name:
      - libnginx-mod-http-modsecurity
      - modsecurity-crs
    state: present
  when: nginx_waf_install
