---
- name: Provision Core Setup
  hosts: all
  become: true
  tags:
    - core
  roles:
    - role: core

- name: Provision Node Services
  hosts: all
  become: true
  tags:
    - node
  roles:
    - role: node

- name: Renew or Issue SSL Certificates with ACME
  hosts: all
  become: true
  tags:
    - cert
    - certificate
    - acme
  roles:
    - role: acme

- name: Provision Nginx & WAF System
  hosts: all
  become: true
  tags:
    - nginx
  roles:
    - role: nginx
