events {}
http {
    log_format json_analytics '{"endpoint":"$endpoint_name"}';
    server {
        listen 8080;
        set $endpoint_name "root";
        access_log access.log json_analytics;

        location /api/ {
            set $endpoint_name "/api/";
            access_log api_access.log json_analytics;
            return 200 "API\n";
        }
    }
}
