---
- name: Retrieve K3s Kubeconfig to Local Workstation
  hosts: k3s_servers
  become: true
  roles:
    - role: ahmz1833.server_setup.k3s
      vars:
        k3s_state: fetch-kubeconfig
        k3s_kubeconfig_local_dest: "~/.kube/config"
