---
- name: Create node_exporter system user
  ansible.builtin.user:
    name: node_exporter
    system: true
    shell: /sbin/nologin
    state: present

- name: Install node_exporter via Binary Install role
  ansible.builtin.include_role:
    name: bin
  vars:
    bin_name: "node_exporter"
    bin_version: "{{ node_exporter_version }}"
    bin_url: "{{ 'https://github.com/prometheus/node_exporter/releases' ~
                 '/download/v' ~ node_exporter_version ~ '/node_exporter-' ~ node_exporter_version ~ '.linux-amd64.tar.gz' }}"
    bin_extract: true
    bin_extract_src: "node_exporter-{{ node_exporter_version }}.linux-amd64/node_exporter"
    bin_version_args: "--version"
    bin_version_regex: 'version\s+([0-9.]+)'
    bin_service_stop: "node_exporter"
    bin_download_locally: "{{ node_download_locally | default(false) }}"

- name: Set node_exporter binary path
  ansible.builtin.set_fact:
    node_exporter_bin_path: "{{ _bin_path | default('/usr/local/bin/node_exporter') }}"

- name: Configure node_exporter systemd service
  ansible.builtin.template:
    src: node_exporter.service.j2
    dest: /etc/systemd/system/node_exporter.service
    mode: '0644'
  notify: Restart node_exporter

- name: Manage node_exporter service state
  ansible.builtin.systemd:
    name: node_exporter
    state: "{{ node_exporter_enabled | ternary('started', 'stopped') }}"
    enabled: "{{ node_exporter_enabled }}"
    daemon_reload: true
